version: '3.4'

services:
    app:
        build:
            context: ./Docker/
            dockerfile: Dockerfile
        image: app/laravel
       #restart: unless-stopped
        tty: true
        volumes: 
            - '.:/var/www/html'
            - './Docker/nginx/laravel.conf:/etc/nginx/conf.d/default.conf'
        #    - './Docker/php/phpfpm:/etc/php/8.0/fpm'
        networks: 
            - app_network
        links:
            - php-fpm
        ports:
            - '80:80'
            - '443:443'
        depends_on: 
            - mysql
            - redis

    #nginx:
    #    build:
    #        context: ./Docker/nginx/
    #        dockerfile: Dockerfile
    #    image: nginx:latest
    #    tty: true
    #    restart: unless-stopped
    #    ports:
    #        - '80:80'
    #        - '443:443'
    #    container_name: nginx
    #    volumes: 
    #        - '.:/usr/share/html'
    #        - './Docker/nginx/laravel.conf:/etc/nginx/conf.d/default.conf'
    #        - './Docker/Log/nginx_error.log:/var/log/nginx/error.log'
    #    networks: 
    #        - app_network  
    #    depends_on: 
    #        - php-fpm
    #        - mysql
    #        - redis
    #        - selenium        


    php-fpm:
        image: php:8.0.1-fpm
        restart: unless-stopped
        ports:
            - '9000:9000'
        container_name: phpfpm
        volumes: 
            - '.:/usr/share/html'
        networks: 
            - app_network

    #selenium:
    #    container_name: selenium
    #    image: 'selenium/standalone-chrome'
    #    volumes:
    #        - '/dev/shm:/dev/shm'
    #    networks:
    #        - app_network   
    
    mysql:
        container_name: mysql
        image: 'mysql:latest'
        restart: unless-stopped
        ports:
            - '${DB_PORT}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        #volumes:
        #    - './Docker/mysql/lib:/var/lib/mysql'
        networks:
            - app_network

    redis:
        container_name: redis
        image: 'redis:latest'
        ports:
            - '${REDIS_PORT}:6379'
        volumes:
            - './Docker/redis:/data'
        networks:
            - app_network

    mailhog:
        container_name: mailhog
        image: 'mailhog/mailhog:latest'
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - app_network

    # memcached:
    #   image: 'memcached:alpine'
    #   ports:
    #       - '11211:11211'
    #   networks:
    #       - sail        

networks: 
  app_network:
    driver: bridge
 