version: '3.4'

services:
  
    #app:
    #    build:
    #        context: ./docker/
    #        dockerfile: Dockerfile
    #    image: app/laravel
    #    restart: unless-stopped
    #    volumes: 
    #        - '.:/usr/share/html'
    #    networks: 
    #        - app_network
    #    depends_on: 
    #        - mysql

    nginx:
        image: nginx:latest
        restart: unless-stopped
        ports:
            - '80:80'
        container_name: nginx
        volumes: 
            - '.:/usr/share/html'
            - './docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf'
        networks: 
            - app_network
        links: 
            - php-fpm
        depends_on: 
            - php-fpm
            - mysql
            - redis
        #    - selenium      

    php-fpm:
        image: php:8.0.1-fpm
        restart: unless-stopped
        ports:
            - '9000:9000'
        container_name: phpfpm
        volumes: 
            - '.:/var/www/html'
        networks: 
            - app_network

    #selenium:
    #    container_name: selenium
    #    image: 'selenium/standalone-chrome'
    #    volumes:
    #        - '/dev/shm:/dev/shm'
    #    networks:
    #        - app_network   
    
    mysql:
        container_name: mysql
        image: 'mysql:latest'
        restart: unless-stopped
        ports:
            - '${DB_PORT}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - './docker/mysql/lib:/var/lib/mysql'
        networks:
            - app_network

    redis:
        container_name: redis
        image: 'redis:latest'
        ports:
            - '${REDIS_PORT}:6379'
        volumes:
            - './docker/redis:/data'
        networks:
            - app_network

    mailhog:
        container_name: mailhog
        image: 'mailhog/mailhog:latest'
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - app_network

    # memcached:
    #   image: 'memcached:alpine'
    #   ports:
    #       - '11211:11211'
    #   networks:
    #       - sail        

networks: 
  app_network:
    driver: bridge
 